//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IDProductos { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }  // nombre de la categoría
        public int IDCategorias { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> Cantidad_Inicial { get; set; }
        public decimal Precio_Venta { get; set; }
        public decimal Precio_Compra { get; set; }
        public string Estado { get; set; }
        public string RutaImagenes { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
